/**
 * Export customization settings and types
 */

export interface ExportCustomizationSettings {
  // Header & Branding
  includeBranding: boolean;           // "Rubber Ducky Live" title
  includeAppSubtitle: boolean;        // "AI Conversation Export" subtitle
  customTitle?: string;               // User's custom document title

  // Message Metadata
  includeMessageRole: boolean;        // "AI Response", "Your Message" headers
  includeTimestamp: boolean;          // Message timestamp
  includeMessageId: boolean;          // Message ID reference
  includeAgentInfo: boolean;          // Which agent was used
  includeTags: boolean;               // Message tags

  // Session Metadata
  includeSessionInfo: boolean;        // Session information block
  includeSessionName: boolean;        // Session name
  includeExportTimestamp: boolean;    // When document was exported

  // Document Structure
  includeFooter: boolean;             // Page numbers and footer
  includeGeneratedBy: boolean;        // "Generated by..." in footer
  includeSeparators: boolean;         // Lines between sections

  // Content Formatting
  fontSize: number;                   // Base font size (8-16pt)
  margin: number;                     // Page margins (10-30mm)
  includeMarkdownStyling: boolean;    // Preserve markdown formatting
  codeBlockStyling: boolean;          // Styled code blocks vs plain text

  // Export Format Preferences
  defaultFormat: 'pdf' | 'word' | 'text';
  fileNameTemplate: string;          // Template for generated filenames
}

export interface ExportPreset {
  id: string;
  name: string;
  description: string;
  settings: ExportCustomizationSettings;
  isDefault?: boolean;
}

// Predefined export presets
export const DEFAULT_EXPORT_PRESETS: ExportPreset[] = [
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Clean content-only export',
    settings: {
      includeBranding: false,
      includeAppSubtitle: false,
      includeMessageRole: false,
      includeTimestamp: false,
      includeMessageId: false,
      includeAgentInfo: false,
      includeTags: false,
      includeSessionInfo: false,
      includeSessionName: false,
      includeExportTimestamp: false,
      includeFooter: true,
      includeGeneratedBy: false,
      includeSeparators: false,
      fontSize: 11,
      margin: 20,
      includeMarkdownStyling: true,
      codeBlockStyling: true,
      defaultFormat: 'pdf',
      fileNameTemplate: '{sessionName}_{messageId}_{timestamp}'
    }
  },
  {
    id: 'standard',
    name: 'Standard',
    description: 'Balanced export with key details',
    settings: {
      includeBranding: false,
      includeAppSubtitle: false,
      includeMessageRole: true,
      includeTimestamp: true,
      includeMessageId: false,
      includeAgentInfo: true,
      includeTags: true,
      includeSessionInfo: false,
      includeSessionName: true,
      includeExportTimestamp: false,
      includeFooter: true,
      includeGeneratedBy: false,
      includeSeparators: true,
      fontSize: 11,
      margin: 20,
      includeMarkdownStyling: true,
      codeBlockStyling: true,
      defaultFormat: 'pdf',
      fileNameTemplate: '{sessionName}_{role}_{timestamp}'
    }
  },
  {
    id: 'detailed',
    name: 'Detailed',
    description: 'Complete export with all metadata',
    settings: {
      includeBranding: true,
      includeAppSubtitle: true,
      includeMessageRole: true,
      includeTimestamp: true,
      includeMessageId: true,
      includeAgentInfo: true,
      includeTags: true,
      includeSessionInfo: true,
      includeSessionName: true,
      includeExportTimestamp: true,
      includeFooter: true,
      includeGeneratedBy: true,
      includeSeparators: true,
      fontSize: 11,
      margin: 20,
      includeMarkdownStyling: true,
      codeBlockStyling: true,
      defaultFormat: 'pdf',
      fileNameTemplate: '{sessionName}_{messageId}_{date}_{time}'
    },
    isDefault: true
  },
  {
    id: 'presentation',
    name: 'Presentation',
    description: 'Clean format for sharing',
    settings: {
      includeBranding: false,
      includeAppSubtitle: false,
      includeMessageRole: false,
      includeTimestamp: false,
      includeMessageId: false,
      includeAgentInfo: false,
      includeTags: false,
      includeSessionInfo: false,
      includeSessionName: true,
      includeExportTimestamp: false,
      includeFooter: true,
      includeGeneratedBy: false,
      includeSeparators: false,
      fontSize: 12,
      margin: 25,
      includeMarkdownStyling: true,
      codeBlockStyling: true,
      defaultFormat: 'pdf',
      fileNameTemplate: '{sessionName}_{date}'
    }
  }
];

export const DEFAULT_EXPORT_SETTINGS: ExportCustomizationSettings = DEFAULT_EXPORT_PRESETS.find(p => p.isDefault)?.settings || DEFAULT_EXPORT_PRESETS[0].settings;